  PREFIX ex: <http://example.com/ns/>
  PREFIX foaf: <http://xmlns.com/foaf/0.1/>

  SELECT ?magician ?name
  WHERE {
    ?s foaf:name "Brian Sletten" ;
       foaf:knows ?magician .
       
    ?magician a ex:Magician ;
       foaf:name ?name .
  }
